version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVE_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    networks:
      - esnet
  ptt_engine:
    image: ptt_engine
    ports:
      - 9000:80
    networks:
      - esnet
    depends_on:
      - elasticsearch
  cerebro:
    image: yannart/cerebro:latest
    volumes:
      - ./cerebro_settings.conf:/opt/cerebro/conf/application.conf
    ports:
      - 19000:9000
    networks:
      - esnet
    depends_on:
      - elasticsearch

networks:
  esnet:

volumes:
  esdata:
